# UltraStrike config

ultra:
  mana-cost: 4
  lightning:
    chance-percent: 4.0
    extra-damage: 3.0
    fire-ticks: 60
  damage-multiplier: 1.6

ui:
  update-ticks: 5
  show-when-zero: false
  show-only-with-sword-or-axe: true

  title: "&d⚡ &fУльтра удар &d⚡"
  ready-text: "&aГОТОВ!"
  used-text: "&cУЛЬТА ИСПОЛЬЗОВАНА!"

  # placeholders: {title} {percent} {bar} {ready} {used}
  format-charging: "{title} &e{percent}% &8[{bar}&8]"
  format-ready: "{title} {ready} &8[{bar}&8]"
  format-used: "{title} &f{used}"

  bar:
    length: 20
    filled: "&a▌"
    empty: "&8▌"

gain-by-damage:
  "1": 5
  "2": 8
  "3": 15
  "4": 20
  "5": 25
  "6": 33
  "7": 39
  "8": 46
  "9": 51
  "10": 60
  "11": 71
  "12": 78
  "13": 81
  "14": 87
  "15": 90
  "16": 98
  "17": 100

hud:
  separator: " &7| "
  show-hp: true
  show-mana: true
  show-ultra-when-zero: true
  hp-format: "&c{hp}/{hp_max} ❤"
  hp-fixed-max: 20
  ultra-format-charging: "&dУльтра удар &e{percent}%"
  ultra-format-ready: "&dУльтра удар &a100%"
  mana-format: "&bМана {mana}/{mana_max} ✨"
  mana-cap: 0  # set 20 to force 20/20 on Java too


particles:
  enabled: true
  charge:
    interval-ticks: 12
    count: 3
    list: ["ENCHANT", "ELECTRIC_SPARK", "END_ROD"]
  ready:
    interval-ticks: 20
    count: 5
    list: ["TOTEM", "END_ROD", "ELECTRIC_SPARK"]
  use:
    count: 18
    list: ["SWEEP_ATTACK", "SOUL_FIRE_FLAME", "CRIT"]
  kill:
    count: 22
    list: ["FIREWORK", "END_ROD", "CRIT"]
