# UltraStrike config

ultra:
  mana-cost: 2
  lightning:
    chance-percent: 4.0
    extra-damage: 3.0
    fire-ticks: 60
    extra-mana-cost: 2
  damage-multiplier: 1.6

ui:
  update-ticks: 5
  show-when-zero: false
  show-only-with-sword-or-axe: false
  title: "&d⚡ &fУльтра удар &d⚡"
  ready-text: "&aГОТОВ!"
  used-text: "&cУЛЬТА ИСПОЛЬЗОВАНА!"

  # placeholders: {title} {percent} {bar} {ready} {used}
  format-charging: "{title} &e{percent}% &8[{bar}&8]"
  format-ready: "{title} {ready} &8[{bar}&8]"
  format-used: "{title} &f{used}"

  bar:
    length: 20
    filled: "&a▌"
    empty: "&8▌"


# Items that can build ultra charge (Material names)
chargeable-items:
  - DIAMOND_SWORD
  - NETHERITE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - STONE_SWORD
  - WOODEN_SWORD
  - DIAMOND_AXE
  - NETHERITE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - STONE_AXE
  - WOODEN_AXE
  - BOW
  - CROSSBOW
  - TRIDENT
  - MACE
gain-by-damage:
  "1": 5
  "2": 8
  "3": 15
  "4": 20
  "5": 25
  "6": 33
  "7": 39
  "8": 46
  "9": 51
  "10": 60
  "11": 71
  "12": 78
  "13": 81
  "14": 87
  "15": 90
  "16": 98
  "17": 100

hud:
  separator: " &7| "
  show-hp: true
  show-mana: true
  show-ultra-when-zero: true
  hp-format: "&c{hp}/{hp_max} ❤"
  hp-fixed-max: 20
  ultra-format-charging: "&dУльтра удар &e{percent}%"
  ultra-format-ready: "&dУльтра удар &a100%"
  mana-format: "&bМана {mana}/{mana_max} ✨"
  mana-cap: 0  # set 20 to force 20/20 on Java too


particles:
  enabled: true

  # Particles while charging ultra (0 = off)
  charge:
    interval-ticks: 20
    count: 0
    list: []

  # Particles when ultra is ready (100%)
  ready:
    interval-ticks: 20
    count: 6
    list: ["SCULK_CHARGE", "TRIAL_OMEN"]

  # Particles when using ultra
  use:
    count: 12
    list: ["TRIAL_SPAWNER_DETECTION_OMINOUS", "TRIAL_OMEN", "SCULK_SOUL"]

  # Particles on kill with ultra
  kill:
    count: 12
    list: ["SCULK_SOUL", "SCULK_CHARGE_POP"]
